# TensorFlow Basics

Import the TensorFlow library:

In [1]:
import tensorflow as tf

Check the version you have installed (it is important that you are not using 2.X versions):

In [2]:
print(tf.__version__)

1.13.0-rc1


## Tensors

Matematical entity of multiple components (or dimensions):

Create a constant string tensor:

In [3]:
hello = tf.constant('Hello')

Tensor does not evaluates its value directly:

In [9]:
print(hello)
print(type(hello))

Tensor("Const:0", shape=(), dtype=string)
<class 'tensorflow.python.framework.ops.Tensor'>


Create a new tensor:

In [6]:
world = tf.constant('World')

Concatenate (add) them:

In [8]:
result = hello + world

The result does not evaluate the concatenation:

In [10]:
print(result)
print(type(result))

Tensor("add:0", shape=(), dtype=string)
<class 'tensorflow.python.framework.ops.Tensor'>


Tensors evaluate themself when a session is created and run:

In [11]:
with tf.Session() as sess:
    print(sess.run(result))

b'HelloWorld'


Another example:

In [13]:
tensor_1 = tf.constant(1)
tensor_2 = tf.constant(2)
print(tensor_1, tensor_2)

Tensor("Const_2:0", shape=(), dtype=int32) Tensor("Const_3:0", shape=(), dtype=int32)


In [14]:
tensor_3 = tensor_1 + tensor_2

In [15]:
with tf.Session() as sess:
    print(sess.run(tensor_3))

3


## Operations

In [26]:
const1 = tf.constant(10)
const2 = tf.constant(20)
val1 = const1 + const2
fill_mat = tf.fill((4,4),10)
myzeros = tf.zeros((4,4))
myones = tf.ones((4,4))
myrandn = tf.random_normal((4,4),mean=0,stddev=0.5)
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

## Interactive Session

Allows you to check results instantly:

In [20]:
sess = tf.InteractiveSession()

In [29]:
print(const1.eval())

10


In [30]:
print(val1.eval())

30


In [32]:
print(fill_mat.eval(),'\n')
print(myzeros.eval(),'\n')
print(myones.eval(),'\n')
print(myrandn.eval(),'\n')
print(myrandu.eval(),'\n')

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]] 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

[[-0.13247214  1.0390062   0.74047446 -0.6173535 ]
 [ 0.17592902  0.0615409  -0.8519868  -0.4316562 ]
 [ 0.03570405  0.16455564  0.2664639   0.1878577 ]
 [ 0.7102586   0.3263166  -0.31279144 -0.36278695]] 

[[0.9428475  0.9645531  0.7295327  0.6830945 ]
 [0.23514426 0.73849034 0.7493056  0.5387925 ]
 [0.14902318 0.26136267 0.8145578  0.6933063 ]
 [0.7068391  0.7297752  0.1704694  0.6307403 ]] 



## Matrix Multiplication

In [33]:
a = tf.constant([ [1,2],
                  [3,4] ])
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [34]:
b = tf.constant([[10],[100]])
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [35]:
result = tf.matmul(a,b)
result.eval()

array([[210],
       [430]], dtype=int32)