# Variables and Placeholders

In [1]:
import tensorflow as tf
import numpy as np
sess = tf.InteractiveSession()

## Variables
Are the values that you are going to optimize.

In [2]:
my_tensor = tf.random_uniform((4,4),0,1)

In [3]:
my_var = tf.Variable(initial_value=my_tensor)

Instructions for updating:
Colocations handled automatically by placer.


In [4]:
print(my_var)

<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32_ref>


#### Note! You must initialize all global variables!

In [5]:
# This line is really important, it is easy to forget!
init = tf.global_variables_initializer()
init.run()

In [6]:
my_var.eval()

array([[0.7757919 , 0.5344827 , 0.1562252 , 0.11261392],
       [0.28091347, 0.04194069, 0.3683889 , 0.60924554],
       [0.869604  , 0.85319245, 0.6904788 , 0.6773833 ],
       [0.09740674, 0.72025096, 0.32087255, 0.1194905 ]], dtype=float32)

In [7]:
sess.run(my_var)

array([[0.7757919 , 0.5344827 , 0.1562252 , 0.11261392],
       [0.28091347, 0.04194069, 0.3683889 , 0.60924554],
       [0.869604  , 0.85319245, 0.6904788 , 0.6773833 ],
       [0.09740674, 0.72025096, 0.32087255, 0.1194905 ]], dtype=float32)

## Placeholders

Are the "inputs" that you give to your graph.

In [8]:
ph = tf.placeholder(tf.float64)

In [9]:
ph = tf.placeholder(tf.int32)

In [10]:
# For shape its common to use (None,# of Features) 
# because None can be filled by number of samples in data
ph = tf.placeholder(tf.float32,shape=(None,5))

## Example

Inputs can come from numpy arrays:

In [13]:
rand_a = np.random.uniform(0,100,(5,5))
rand_b = np.random.uniform(0,100,(5,1))
print(rand_a,'\n')
print(rand_b,'\n')

[[14.83902302 74.62338091 82.13472311 73.11625063 37.780147  ]
 [22.97456395 81.22128325 94.26192122  8.20889298 10.38998105]
 [61.47097245 41.76166135 12.46722127  2.36653522 11.30794807]
 [12.85614124 42.76346118 99.03323024 71.75804188  4.94880503]
 [65.27963957 37.5608487  77.34310654 30.31902144  2.5728157 ]] 

[[21.09041542]
 [27.58711454]
 [69.17841395]
 [46.71877673]
 [46.68546405]] 



### Placeholders

You do not need to define the dimensions explicitly:

In [14]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)

### Operations

In [15]:
add_op = a+b # tf.add(a,b)
mult_op = a*b #tf.multiply(a,b)

### Running Sessions  to create Graphs with Feed Dictionaries

In [16]:
with tf.Session() as sess:
    add_result = sess.run(add_op,feed_dict={a:rand_a,b:rand_b})
    print(add_result)
    
    print('\n')
    
    mult_result = sess.run(mult_op,feed_dict={a:rand_a,b:rand_b})
    print(mult_result)

[[ 35.92944   95.7138   103.225136  94.206665  58.870564]
 [ 50.561676 108.808395 121.84904   35.796005  37.977097]
 [130.64938  110.94008   81.64564   71.54495   80.48636 ]
 [ 59.574917  89.48224  145.75201  118.47682   51.66758 ]
 [111.9651    84.24631  124.02857   77.004486  49.258278]]


[[ 312.96115 1573.8381  1732.2554  1542.0521   796.799  ]
 [ 633.80194 2240.661   2600.4146   226.45967  286.6296 ]
 [4252.4644  2889.0054   862.4626   163.71315  782.2659 ]
 [ 600.62317 1997.8567  4626.7114  3352.448    231.2021 ]
 [3047.61    1753.5455  3610.7988  1415.4575   120.11309]]
