In [3]:
import tensorflow as tf
import numpy as np
sess = tf.InteractiveSession()

# Variables y Placeholders

In [4]:
my_tensor = tf.random_uniform((4,4), 0, 1)

In [5]:
my_var = tf.Variable(initial_value=my_tensor)

Instructions for updating:
Colocations handled automatically by placer.


In [6]:
print(my_var)

<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32_ref>


Inicializar variables:

In [7]:
init = tf.global_variables_initializer()
init.run()

In [8]:
my_var.eval()

array([[0.05373049, 0.9865644 , 0.39076686, 0.11859226],
       [0.83903563, 0.49888468, 0.4123106 , 0.7631725 ],
       [0.4475019 , 0.7381072 , 0.19355321, 0.9880121 ],
       [0.5986153 , 0.9898772 , 0.21553135, 0.11127865]], dtype=float32)

## Placeholders

In [9]:
rand_a = np.random.uniform(0,100,(5,5))
rand_b = np.random.uniform(0,100,(5,1))
print(rand_a, '\n')
print(rand_b, '\n')

[[62.45471012 97.84129961 28.1041045  24.46408835 64.58886122]
 [31.43593191 59.76892076 49.47126567 90.0665763   1.07881039]
 [ 4.7386105  93.85715056 96.65839494 81.73125831 87.47093859]
 [17.42619878 65.62312227 55.22935889 41.35911001 57.25887328]
 [58.36864511 20.7459899  93.30746235 74.33615588 23.95016661]] 

[[18.95800273]
 [94.96410213]
 [44.78535771]
 [17.29420152]
 [90.76136371]] 



### Placeholders

In [10]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)

### Operaciones

In [12]:
add_op = a + b
mult_op = a * b

In [15]:
with tf.Session() as sess:
    add_result = sess.run(add_op, feed_dict={a:rand_a, b:rand_b})
    print(add_result, '\n')
    
    mult_result = sess.run(mult_op, feed_dict={a:rand_a, b:rand_b})
    print(mult_result, '\n')

[[ 81.41271  116.7993    47.062107  43.42209   83.54686 ]
 [126.40004  154.73303  144.43536  185.03067   96.042915]
 [ 49.523968 138.6425   141.44376  126.51662  132.2563  ]
 [ 34.720398  82.91733   72.52356   58.653313  74.55307 ]
 [149.13     111.507355 184.06882  165.09752  114.711525]] 

[[1184.0166  1854.8756   532.79767  463.79025 1224.4757 ]
 [2985.2852  5675.902   4697.994   8553.092    102.44826]
 [ 212.22035 4203.426   4328.881   3660.3635  3917.4175 ]
 [ 301.3722  1134.8995   955.14764  715.27277  990.24646]
 [5297.6177  1882.9343  8468.712   6746.851   2173.7498 ]] 

